---
development:
  dialect: postgres
  database: rpg_api_development
  user: buffalo
  password: buffalo
  host: docker
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://buffalo:buffalo@docker:5432/rpg_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://buffalo:buffalo@docker:5432/rpg_api_production?sslmode=disable"}}
