version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: buffalo
      POSTGRES_PASSWORD: buffalo
    ports:
      - 5432:5432
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
